# Site settings
title: Phil Ellsworth
twitter_username: philellsworth
linkedin_username: philellsworth
facebook_username: philellsworth
name: Phil Ellsworth

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://philellsworth.com/
 - title: poems.philellsworth.com
   url: https://poems.philellsworth.com/
 - title: My Father's War
   url: https://ww2.philellsworth.com
 - title: GitHub
   url: https://github.com/philellsworth
 - title: StackOverflow
   url: https://stackoverflow.com/users/3747047/philellsworth
 #- title: DZone
 #  url: 
 - title: LinkedIn
   url: https://www.linkedin.com/in/philellsworth

#Any buzzword skills you want to include
skills:
 - HTML
 - CSS
 - Adobe InDesign
 - Adobe Illustrator
 - Adobe Photoshop
 - Adobe Dreamweaver
 - WordPress
 - Jekyll
 - Commercial Photography
 - Professional Editing and Reporting

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://philellsworth.com/feed/

#Work experience is required
roles:
 - title: Economist
   start: 2017
   end: Ongoing
   employer: Texas Workforce Commission
   description: Texas Workforce Commission, Labor Market and Career Information – October 2017 to present. Validate macro-level data through research and analysis, to document and reconcile employment and wages by ownership, industry, and location, and validate micro-level data to document and reconcile employment, wages, and contributions. Document, explain, and track economic events to aid in analysis. Assign North American Industry Classification System (NAICS) industry codes and other data codes using standard procedures. Edit multiple worksite and wage reports for accuracy, and to document acquisitions and divestitures.
 - title: Substitute Teacher
   start: 2017
   end: 2017
   employer: Cypress-Fairbanks School District, Cypress TX
   description: Perform the duties of a teacher in the teacher’s absence, in accordance with instructions and policies of the teacher, school and district. Includes administering tests, maintaining classroom discipline. Instructs students at the high school level in a wide array of topics.
 - title: Hardlines Sales Team Member
   start: 2015
   end: Ongoing
   employer: Target Corporation
   description: Primary duties include assisting guests in a busy retail environment, handling cash and inventory, restocking merchandise and assisting other team members.
 - title: Publications and Web Editor
   start: 2005
   end: 2015
   employer: Wyoming Dept. of Workforce Services, Research & Planning, Casper, WY
   description: Primary duties were editing and layout of hard-copy publications, and development of websites and web content for the state’s websites related to Labor Market Information and statistical analysis conducted by the Wyoming Department of Workforce Services' Research & Planning section. Oversaw publication of the monthly Wyoming Labor Force Trends, the Wyoming Workforce Annual Report, and numerous other publications and web pages. Served as Wyoming's representative on the Analyst Resource Center’s Workforce Information Database consortium from 2007-2015 and as chair of the national ARC Education and Communication Subcommittee.

#Education is required
education:
 - level: Bachelor of Science (B.S.)
   date: 1983
   subject: Photography
   school: Sam Houston State University

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - philellsworth/philellsworth.github.io.git
 - philellsworth/pinteresting

#Stackoverflow flair is optional
#stackoverflow:
   # profileurl: http://stackoverflow.com/users/258813/rhinds
   #flairimageurl: http://stackoverflow.com/users/flair/258813.png

#Mobile apps section is optional
#apps:
 #- name: Chuck the Quiz
   #platform: Android
   #url: https://play.google.com/store/apps/details?id=com.tmm.android.chuck&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS50bW0uYW5kcm9pZC5jaHVjayJd
   #description: A basic early Android app (open sourced)

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
   #<strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
   #<strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   #<strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   #I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   #As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   #I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
